Fix first deploy cluster creation
veezor/maestro pull request #76
Opened 2023-10-09 17:47 UTC by MatheusdeMelo

Fix the ECS cluster creation in the first deploy on CodeBuild.

2023-10-13 17:15 UTC, fagianijunior commented on provision.sh
>  			#echo "Repository slug is '$2'"
unnecessary comment

2023-10-13 17:16 UTC, fagianijunior commented on provision.sh
> +            #echo "Cluster ID is '$2'"
unnecessary commnet

2023-10-13 17:17 UTC, fagianijunior requested changes
Needs to remove the unnecessary comment on code.

2023-10-18 17:53 UTC, MatheusdeMelo commented
> Needs to remove the unnecessary comment on code.

With the commit "Remove comments" this requested has be changed.

2023-10-19 19:59 UTC, fagianijunior approved these changes
]ok

2023-10-19 19:59 UTC, merged